services:
  - type: web
    name: brain-agriculture-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health/live
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: "false"
